name: Deploy VOLK Sunglasses

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Delegando a Beget
        run: echo "El despliegue automático está delegado a Beget. Github Actions en verde."
